# Generated by Django 5.1.1 on 2024-10-21 19:50

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tstapp', '0002_remove_brands_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='industry',
        ),
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='brands',
            name='img',
            field=models.ImageField(blank=True, upload_to='imgs/brands/', verbose_name='Лого'),
        ),
        migrations.AddField(
            model_name='categories',
            name='img',
            field=models.ImageField(blank=True, upload_to='imgs/cats/', verbose_name='Лого'),
        ),
        migrations.AddField(
            model_name='images',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Товар в наличии'),
        ),
        migrations.DeleteModel(
            name='Industries',
        ),
    ]
