# Generated by Django 5.1.1 on 2024-11-08 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tstapp', '0003_remove_product_industry_alter_brands_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='SubCats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Подкатегория')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tstapp.categories', verbose_name='Категорея')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subCat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tstapp.subcats', verbose_name='Подкатегорея'),
        ),
    ]
