# Generated by Django 5.1.3 on 2025-01-23 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tstapp', '0004_alter_brands_name_alter_categories_name_subcats_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcats',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AddField(
            model_name='product',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='Популярный'),
        ),
        migrations.AddField(
            model_name='product',
            name='prom_week',
            field=models.BooleanField(default=False, verbose_name='Товар недели'),
        ),
        migrations.AlterField(
            model_name='images',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tstapp.product', verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='images',
            name='src',
            field=models.ImageField(upload_to='imgs/products/', verbose_name='Фаил'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.SlugField(max_length=32, unique=True, verbose_name='Артикул'),
        ),
    ]
