# Generated by Django 5.1.1 on 2025-01-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tstapp', '0005_alter_subcats_options_alter_images_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='Популярный'),
        ),
        migrations.AddField(
            model_name='product',
            name='prom_week',
            field=models.BooleanField(default=False, verbose_name='Товар недели'),
        ),
    ]
