# Generated by Django 5.1.11 on 2025-07-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tstapp', '0007_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='img',
            field=models.ImageField(default='imgs/articles/default.jpg', upload_to='imgs/articles/', verbose_name='Preview'),
        ),
    ]
