# Generated by Django 5.1.3 on 2025-07-29 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tstapp', '0005_alter_subcats_options_product_popular_and_more'),
        ('tstapp', '0008_articles_img'),
    ]

    operations = [
    ]
